### ISSUE TITLE
empty readme, if pod after __DATA__, __END__

### ISSUE THREAD

**Issue by wollmers** [DarwinAwardWinner/Dist-Zilla-Plugin-ReadmeAnyFromPod#22]
Used via Dist::Milla it creates an empty README.md, if the pod is placed in an package after

    package Foo;
    # some code
    __DATA__
    @@ something here
     __END__
     =pod here

Had to move the pod before __DATA__

See https://github.com/wollmers/Mojolicious-Plugin-ServerInfo/commits/master/README.md

Other readers like perldoc have no problems extracting the pod.

**Comment by DarwinAwardWinner** [comment]
ReadmeAnyFromPod uses PPI to extract the POD, so I guess this is a bug in PPI? 

https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-ReadmeAnyFromPod/blob/master/lib/Dist/Zilla/Plugin/ReadmeAnyFromPod.pm#L373-376]

**Comment by DarwinAwardWinner** [comment]
Sure enough, it is a PPI Issue: 
https://github.com/adamkennedy/PPI/issues/15
https://github.com/adamkennedy/PPI/issues/16

I'm going to close this since there's nothing I can do about it in this module.
