### ISSUE TITLE
Help Request: how to include pictures

### ISSUE THREAD

**Issue by atoomic** [DarwinAwardWinner/Dist-Zilla-Plugin-ReadmeAnyFromPod#28]
Not sure if it's possible and if so what is the syntax to handle images added to the POD to make sure they are added to the HTML and to the Markdown?

Using one of the `=for HTML` tag will only apply to the HTML rendering and not to the markdown as expected.

As described by https://perlmaven.com/how-to-add-images-to-cpan
```
=for HTML <p><img src="https://szabgab.com/img/SVG/circle.png" alt="SVG example circle" /></p>
```
what is the best practice to have the pictures added to the Markdown and Html?

**Comment by DarwinAwardWinner** [comment]
This module just uses Pod::Markdown to convert POD to markdown, so I think this is going to be a question for the author of Pod::Markdown. I don't know the answer

**Comment by atoomic** [comment]
thanks for your answer
